name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest
      - name: Configure
        run: emcmake cmake -S . -B build
      - name: Build
        run: cmake --build build --config Release
